import {EmojiData} from '@ctrl/ngx-emoji-mart/ngx-emoji/data/data.interfaces';

export const ListEmoji: EmojiData[] = [
  {
    id: 'grinning',
    name: 'Grinning Face',
    colons: ':grinning:',
    emoticons: [],
    text: ':D',
    native: '😀',
    keywords: [],
    hidden: [],
    shortName: 'grinning',
    shortNames: ['grinning'],
    sheet: [1, 1],
    skinVariations: []
  },
  {
    colons: ':smiley:',
    emoticons: ['=-)', '=)'],
    hidden: [],
    id: 'smiley',
    keywords: ['face', 'happy', 'joy', 'haha', ':D', ':)', 'smile', 'funny'],
    name: 'Smiling Face with Open Mouth',
    native: '😃',
    set: 'apple',
    sheet: [30, 35],
    shortName: 'smiley',
    shortNames: ['smiley'],
    skinVariations: [],
    text: ' :)',
    unified: '1F603',
  },
  {
    colons: ':heart_eyes:',
    emoticons: [],
    hidden: [],
    id: 'heart_eyes',
    keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart'],
    name: 'Smiling Face with Heart-Shaped Eyes',
    native: '😍',
    set: 'apple',
    sheet: [30, 45],
    shortName: 'heart_eyes',
    shortNames: ['heart_eyes'],
    skinVariations: [],
    text: '',
    unified: '1F60D',
  },
  {
    colons: ':laughing:',
    emoticons: [':>', ':->'],
    hidden: [],
    id: 'laughing',
    keywords: ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'glad', 'XD', 'laugh'],
    name: 'Smiling Face with Open Mouth and Tightly-Closed Eyes',
    native: '😆',
    set: 'apple',
    sheet: [30, 38],
    shortName: 'laughing',
    shortNames: ['laughing', 'satisfied'],
    skinVariations: [],
    text: '',
    unified: '1F606',
  },
  {
    colons: ':shushing_face:',
    emoticons: [],
    hidden: [],
    id: 'shushing_face',
    keywords: [],
    name: 'Face with Finger Covering Closed Lips',
    native: '🤫',
    set: 'apple',
    sheet: [38, 44],
    shortName: 'shushing_face',
    shortNames: ['shushing_face', 'face_with_finger_covering_closed_lips'],
    skinVariations: [],
    text: '',
    unified: '1F92B',
  },
  {
    colons: ':grimacing:',
    emoticons: [],
    hidden: [],
    id: 'grimacing',
    keywords: ['face', 'grimace', 'teeth'],
    name: 'Grimacing Face',
    native: '😬',
    set: 'apple',
    sheet: [31, 18],
    shortName: 'grimacing',
    shortNames: ['grimacing'],
    skinVariations: [],
    text: '',
    unified: '1F62C',
  },
  {
    colons: ':stuck_out_tongue_winking_eye:',
    emoticons: [';p', ';-p', ';b', ';-b', ';P', ';-P'],
    hidden: [],
    id: 'stuck_out_tongue_winking_eye',
    keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue'],
    name: 'Face with Stuck-out Tongue and Winking Eye',
    native: '😜',
    set: 'apple',
    sheet: [31, 2],
    shortName: 'stuck_out_tongue_winking_eye',
    shortNames: ['stuck_out_tongue_winking_eye'],
    skinVariations: [],
    text: ';p',
    unified: '1F61C',
  },
  {
    colons: ':zany_face:',
    emoticons: [],
    hidden: [],
    id: 'zany_face',
    keywords: [],
    name: 'Grinning Face with One Large and One Small Eye',
    native: '🤪',
    set: 'apple',
    sheet: [38, 43],
    shortName: 'zany_face',
    shortNames: ['zany_face', 'grinning_face_with_one_large_and_one_small_eye'],
    skinVariations: [],
    text: '',
    unified: '1F92A',
  },
  {
    colons: ':stuck_out_tongue:',
    emoticons: [':p', ':-p', ':P', ':-P', ':b', ':-b'],
    hidden: [],
    id: 'stuck_out_tongue',
    keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'tongue'],
    name: 'Face with Stuck-out Tongue',
    native: '😛',
    set: 'apple',
    sheet: [31, 1],
    shortName: 'stuck_out_tongue',
    shortNames: ['stuck_out_tongue'],
    skinVariations: [],
    text: ':p',
    unified: '1F61B',
  },
  {
    colons: ':smiley_cat:',
    emoticons: [],
    hidden: [],
    id: 'smiley_cat',
    keywords: ['animal', 'cats', 'happy', 'smile'],
    name: 'Smiling Cat Face with Open Mouth',
    native: '😺',
    set: 'apple',
    sheet: [31, 32],
    shortName: 'smiley_cat',
    shortNames: ['smiley_cat'],
    skinVariations: [],
    text: '',
    unified: '1F63A',
  },
];


